### DISCUSSION TITLE
How to use it

### DISCUSSION THREAD

**Discussion by fertkir** [fertkir/prowlarr-telegram-client#3] [Q&A]
![Screencast](https://github.com/fertkir/prowlarr-telegram-client/assets/5433737/65898a6a-1316-4be0-a0a4-9239669dd779)

**Comment by nikolachakalov** [comment]
Hello! Thank you for this great tool. I just tried it out and it works as expected :) I have one question though: Is there a way to make the bot only query one of my specified Prowlarr trackers? I have somewhere around 10 trackers in Prowlarr, but I need the prowlarr-telegram-client to only query one of these trackers, as it fits the use case I have for this client. Having all other trackers spam the results and deliver irrelevant content. Is there a way to narrow down the API call to prowlarr to only query one of my trackers? Thank you!

**Reply by fertkir** [reply]
Hi, thank you!
This is Prowlarr's API for search: https://prowlarr.com/docs/api/#/Search/get_api_v1_search
I suspect that the indexerIds is what you need.
We can make them configurable through env variables.
I'll take a look maybe on the weekend.

**Comment by nikolachakalov** [comment]
Thank you! This sounds like it might be the right way to go, yes. Prowlarr shows the API endpoint for each of the trackers in the UI, so that sounds about right. Have a great week.

**Reply by fertkir** [reply]
Now you can add a comma-separated list of indexer ids in PROWLARR_INDEXER_IDS env variable

**Reply by nikolachakalov** [reply]
Thank you! I will try it out next week. Thank you for implementing this -- I appreciate the effort 🙏🏻🙏🏻🙏🏻

**Reply by nikolachakalov** [reply]
I am trying it out now, but I am not sure about the exact formatting of the env variable:

```
services:
  prowlarr-tg-client:
    container_name: prowlarrtelegram
    image: ghcr.io/fertkir/prowlarr-telegram-client:main
    user: "1000:1000" # TODO replace with your user and group ids
    networks:
      - multimedia_default
    environment:
      - PROWLARR_API_KEY=XXX# TODO: replace with your Prowlarr api key
      - PROWLARR_BASE_URL=http://prowlarr:9696
      - RUST_LOG=info
      - TELOXIDE_TOKEN=XXX # TODO: replace with your telegram token
      - PROWLARR_INDEXER_IDS=19
    restart: unless-stopped
```

What am I doing wrong? I need to query the bot for results from just one indexer with the ID 19. I am still getting results from all registered Prowlarr indexers. I think the problem is on my side and as mentioned, I think the problem is that I haven't defined the PROWLARR_INDEXER_IDS properly, even though the container spins up without any issues. Thank you for your feedback!
